/**
 * Extracts the exact lucide-react icon geometry the product uses and writes it
 * to kit/icons.js. Same package, same version, same paths — the marketing
 * assets and the app draw identical icons.
 *
 *   node marketing/tools/gen-icons.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ICON_DIR = path.resolve(HERE, '../../node_modules/lucide-react/dist/esm/icons');
const OUT = path.resolve(HERE, '../kit/icons.js');

// Every icon that appears in the replicated screens, in kebab-case (the
// filename lucide ships).
const ICONS = [
  'bar-chart-3', 'message-square', 'users', 'tags', 'message-square-reply',
  'file-text', 'briefcase-business', 'check-square', 'send', 'settings',
  'target', 'user-cog', 'users-round', 'bot', 'sparkles', 'building-2',
  'shield-check', 'plus', 'upload', 'search', 'bell', 'moon', 'sun',
  'refresh-cw', 'mail', 'arrow-up-right', 'trending-up', 'flame',
  'message-circle', 'info', 'paperclip', 'mic', 'smile', 'chevron-down',
  'chevron-right', 'chevron-left', 'layout-template', 'tag', 'pin',
  'clock', 'inbox', 'check', 'check-check', 'zap', 'globe', 'lock',
  'play', 'pause', 'more-vertical', 'x', 'phone', 'video', 'image',
  'circle-dollar-sign', 'activity', 'gauge', 'workflow', 'brain',
  'megaphone', 'calendar', 'star', 'shield', 'database', 'git-branch',
  'arrow-right', 'external-link', 'filter', 'download', 'eye',
  'user-round', 'alert-triangle', 'shopping-cart', 'pencil', 'trash-2',
  'log-out', 'book-open', 'headphones', 'timer', 'percent', 'wallet',
  'list-checks', 'reply', 'forward', 'copy', 'bell-off', 'bookmark-check',
  'minus', 'circle-check', 'circle-x', 'sparkle', 'layers', 'link',
];

// lucide renamed these; the app still imports the old React name, so keep the
// old key and read the file the package actually ships today.
const ALIAS = {
  'check-square': 'square-check',
  'more-vertical': 'ellipsis-vertical',
  'alert-triangle': 'triangle-alert',
};

const ATTR_ORDER = ['d', 'cx', 'cy', 'r', 'x', 'y', 'width', 'height', 'rx', 'ry', 'x1', 'y1', 'x2', 'y2', 'points', 'transform'];

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

/** Parse the `createLucideIcon("Name", [ ["tag", {…}], … ])` array literal. */
function parse(src) {
  const start = src.indexOf('createLucideIcon(');
  const open = src.indexOf('[', start);
  const close = src.lastIndexOf(']);');
  const body = src.slice(open, close + 1);
  const out = [];
  // Nodes are pretty-printed across several lines once an attribute is long,
  // so every separator has to tolerate whitespace.
  const nodeRe = /\[\s*"([a-zA-Z]+)"\s*,\s*\{([^}]*)\}\s*\]/g;
  let m;
  while ((m = nodeRe.exec(body))) {
    const tag = m[1];
    const attrs = {};
    const attrRe = /([a-zA-Z0-9-]+):\s*"([^"]*)"/g;
    let a;
    while ((a = attrRe.exec(m[2]))) {
      if (a[1] === 'key') continue;
      attrs[a[1]] = a[2];
    }
    const ordered = Object.keys(attrs).sort(
      (x, y) => (ATTR_ORDER.indexOf(x) + 1 || 99) - (ATTR_ORDER.indexOf(y) + 1 || 99),
    );
    out.push(`<${tag} ${ordered.map((k) => `${k}="${esc(attrs[k])}"`).join(' ')}/>`);
  }
  return out.join('');
}

const entries = {};
const missing = [];
for (const name of ICONS) {
  try {
    const src = await readFile(path.join(ICON_DIR, `${ALIAS[name] ?? name}.js`), 'utf8');
    const inner = parse(src);
    if (!inner) throw new Error('no nodes');
    entries[name] = inner;
  } catch {
    missing.push(name);
  }
}

const banner = `/* AUTO-GENERATED by marketing/tools/gen-icons.mjs — do not edit by hand.
   Geometry extracted from lucide-react (ISC), the same icon set the product
   renders, so marketing art and product UI never drift apart. */\n`;

const js = `${banner}window.ICONS = ${JSON.stringify(entries, null, 0)};

/** Render a lucide icon exactly as the product does (24-grid, 2px stroke). */
window.icon = function icon(name, cls = '', stroke = 2) {
  const body = window.ICONS[name];
  if (!body) return '';
  return '<svg class="ic ' + cls + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
    'stroke-width="' + stroke + '" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
    body + '</svg>';
};
`;

await writeFile(OUT, js, 'utf8');
console.log(`icons: ${Object.keys(entries).length} written → ${path.relative(process.cwd(), OUT)}`);
if (missing.length) console.log(`missing (skipped): ${missing.join(', ')}`);
