/**
 * Downloads the exact webfonts the product loads in `app/globals.css`
 * (Plus Jakarta Sans + IBM Plex Sans Arabic) and inlines them, base64, into
 * kit/fonts.css.
 *
 * Rendering happens in headless Chrome off a file:// URL. A remote @import
 * would race the screenshot — half the assets would come out in Segoe UI, and
 * you would not find out until you looked at 40 finished PNGs. Embedded fonts
 * make every render byte-identical and offline-safe.
 *
 *   node marketing/tools/gen-fonts.mjs
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, '../kit/fonts.css');

// A modern UA is what makes the CSS2 endpoint serve woff2 instead of ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const FAMILIES = [
  'Plus+Jakarta+Sans:wght@400;500;600;700;800',
  'IBM+Plex+Sans+Arabic:wght@400;500;600;700',
];

async function fetchCss(family) {
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${family} → HTTP ${res.status}`);
  return res.text();
}

/**
 * Google ships one @font-face per unicode-range subset. We only render Latin
 * and Arabic, so dropping the rest (cyrillic, greek, vietnamese…) cuts the
 * embedded payload by roughly two thirds with no visible difference.
 */
function wantedBlocks(css) {
  return css
    .split(/(?=@font-face)/)
    .filter((b) => b.includes('@font-face'))
    .filter((b) => {
      const m = /\/\*\s*([a-z-]+)\s*\*\//i.exec(b);
      const subset = m ? m[1] : 'latin';
      return ['latin', 'latin-ext', 'arabic'].includes(subset);
    });
}

async function inline(block) {
  const m = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block);
  if (!m) return null;
  const res = await fetch(m[1], { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`font file → HTTP ${res.status}`);
  const b64 = Buffer.from(await res.arrayBuffer()).toString('base64');
  return block.replace(m[0], `url(data:font/woff2;base64,${b64})`);
}

const out = [
  '/* AUTO-GENERATED by marketing/tools/gen-fonts.mjs — do not edit by hand.',
  '   Same families the product loads in app/globals.css, embedded so headless',
  '   renders never race a network font fetch. */',
];

let count = 0;
for (const family of FAMILIES) {
  const blocks = wantedBlocks(await fetchCss(family));
  for (const block of blocks) {
    const inlined = await inline(block);
    if (inlined) {
      out.push(inlined.trim());
      count++;
    }
  }
}

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, out.join('\n\n') + '\n', 'utf8');
console.log(`fonts.css → ${count} faces, ${(Buffer.byteLength(out.join('')) / 1024).toFixed(0)} KB`);
